-- MySQL Script generated by MySQL Workbench
-- Wed Mar  7 20:23:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bicicletaria_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bicicletaria_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bicicletaria_db` DEFAULT CHARACTER SET utf8 ;
USE `bicicletaria_db` ;

-- -----------------------------------------------------
-- Table `bicicletaria_db`.`listaPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicicletaria_db`.`listaPerfil` (
  `idListaPerfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idListaPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bicicletaria_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicicletaria_db`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `idListaPerfil_Usuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idListaPerfil_Usuario_idx` (`idListaPerfil_Usuario` ASC),
  CONSTRAINT `idListaPerfil_Usuario`
    FOREIGN KEY (`idListaPerfil_Usuario`)
    REFERENCES `bicicletaria_db`.`listaPerfil` (`idListaPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bicicletaria_db`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicicletaria_db`.`pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `idUsuario_Pessoa` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `idUsuario_Pessoa_idx` (`idUsuario_Pessoa` ASC),
  CONSTRAINT `idUsuario_Pessoa`
    FOREIGN KEY (`idUsuario_Pessoa`)
    REFERENCES `bicicletaria_db`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
